from enum import Enum


class Event(Enum):
    UNKNOWN = 0
    PLAYER_DIED = 1
    PLAYER_ATTACKED = 2
    NEW_LOCATION_DISCOVERED = 3
    PLAYER_WENT_AIRBORNE = 4
    GAME_TIME_PASSED = 5
    PLAYER_TOOK_DAMAGE = 6
    TARGET_KILLED = 7
    ITEM_PICKED_UP = 8
    ENCOUNTER_STARTED = 9
    ENCOUNTER_ENDED = 10
    ENCOUNTER_ZONE_LEFT = 11
    ENCOUNTER_ZONE_ENTERED = 12
